// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxnDSHtvKVjoPpzeJJ8JfCVF_Ofy4CsPs',
    appId: '1:54469841565:android:6b8f5caf504693e0a6fa74',
    messagingSenderId: '54469841565',
    projectId: 'swim-ddaad',
    storageBucket: 'swim-ddaad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRrS5N0SHHOY4msEQ__xdjKB38xgnKLnc',
    appId: '1:54469841565:ios:a378633235b2cba6a6fa74',
    messagingSenderId: '54469841565',
    projectId: 'swim-ddaad',
    storageBucket: 'swim-ddaad.firebasestorage.app',
    iosBundleId: 'com.example.swim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRrS5N0SHHOY4msEQ__xdjKB38xgnKLnc',
    appId: '1:54469841565:ios:a378633235b2cba6a6fa74',
    messagingSenderId: '54469841565',
    projectId: 'swim-ddaad',
    storageBucket: 'swim-ddaad.firebasestorage.app',
    iosBundleId: 'com.example.swim',
  );
}
